### ISSUE TITLE
3.6.14 XPrivacy not enabled (4.4.4)

### ISSUE THREAD

**Issue by an0n981** [M66B/XPrivacy#2206]
unchecking/rechecking in XPosed doesn't help. Reboot or shutdown/power on doesn't help.

```
W/XPrivacy( 4396): No client for uid=0 /Log=null uid=10071 pid=4396
W/XPrivacy( 4396): java.lang.Exception: StackTrace
W/XPrivacy( 4396):      at biz.bokhorst.xprivacy.er.d(SourceFile:264)
W/XPrivacy( 4396):      at biz.bokhorst.xprivacy.en.a(SourceFile:806)
W/XPrivacy( 4396):      at biz.bokhorst.xprivacy.en.c(SourceFile:781)
W/XPrivacy( 4396):      at biz.bokhorst.xprivacy.en.b(SourceFile:773)
W/XPrivacy( 4396):      at biz.bokhorst.xprivacy.fy.a(SourceFile:82)
W/XPrivacy( 4396):      at biz.bokhorst.xprivacy.ApplicationEx.onCreate(SourceFile:13)
W/XPrivacy( 4396):      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
W/XPrivacy( 4396):      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4473)
W/XPrivacy( 4396):      at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
W/XPrivacy( 4396):      at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
W/XPrivacy( 4396):      at android.app.ActivityThread.handleBindApplication(Native Method)
W/XPrivacy( 4396):      at android.app.ActivityThread.access$1500(ActivityThread.java:144)
W/XPrivacy( 4396):      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
W/XPrivacy( 4396):      at android.os.Handler.dispatchMessage(Handler.java:102)
W/XPrivacy( 4396):      at android.os.Looper.loop(Looper.java:136)
W/XPrivacy( 4396):      at android.app.ActivityThread.main(ActivityThread.java:5146)
W/XPrivacy( 4396):      at java.lang.reflect.Method.invokeNative(Native Method)
W/XPrivacy( 4396):      at java.lang.reflect.Method.invoke(Method.java:515)
W/XPrivacy( 4396):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
W/XPrivacy( 4396):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
W/XPrivacy( 4396):      at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
W/XPrivacy( 4396):      at dalvik.system.NativeStart.main(Native Method)
```

Complete boot log (no debugging): https://gist.github.com/an0n981/0ec49b9b5a8bb954098f

**Comment by M66B** [comment]
This is caused by running an older Xposed version:

```
I/Xposed  (  543): java.lang.NoClassDefFoundError: de/robv/android/xposed/SELinuxHelper
I/Xposed  (  543):      at biz.bokhorst.xprivacy.XPrivacy.initZygote(SourceFile:46)
I/Xposed  (  543):      at de.robv.android.xposed.XposedBridge.loadModule(XposedBridge.java:437)
I/Xposed  (  543):      at de.robv.android.xposed.XposedBridge.loadModules(XposedBridge.java:386)
I/Xposed  (  543):      at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:120)
I/Xposed  (  543):      at dalvik.system.NativeStart.main(Native Method)
```

I am going to workaround this.
