### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by horuga23** [M66B/XPrivacy#2291]
Hi,

On start I get the message, that an internal test failed. Here are the support informations.

Best regards
h

XPrivacy: 3.6.19 
Android: 5.1 (SDK 22) 

Brand: lge 
Manufacturer: LGE 
Model: LG-H815 
Product: p1_global_com 
Device: p1 
Host: LGEACI5R10 
Display: LMY47D 
Id: LMY47D 

java.lang.NoSuchFieldException: mSleeping uid=1000
java.lang.NoSuchFieldException: mSleeping
at java.lang.Class.getDeclaredField(Class.java:890)
at biz.bokhorst.xprivacy.XActivityManagerService.b(SourceFile:192)
at biz.bokhorst.xprivacy.XPrivacy$XMethodHook.afterHookedMethod(SourceFile:660)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:682)
at com.android.server.am.ActivityManagerService.updateSleepIfNeededLocked(<Xposed>)
at com.android.server.am.ActivityManagerService.setLockScreenShown(ActivityManagerService.java:10780)
at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:668)
at com.android.server.am.ActivityManagerService.setLockScreenShown(<Xposed>)
at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:1336)
at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2521)
at com.android.server.am.ActivityManagerServiceEx.onTransact(ActivityManagerServiceEx.java:448)
at android.os.Binder.execTransact(Binder.java:446)
at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:668)
at android.os.Binder.execTransact(<Xposed>)

java.lang.NoSuchFieldException: mSleeping uid=1000
java.lang.NoSuchFieldException: mSleeping
at java.lang.Class.getDeclaredField(Class.java:890)
at biz.bokhorst.xprivacy.XActivityManagerService.b(SourceFile:192)
at biz.bokhorst.xprivacy.XPrivacy$XMethodHook.afterHookedMethod(SourceFile:660)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:682)
at com.android.server.am.ActivityManagerService.updateSleepIfNeededLocked(<Xposed>)
at com.android.server.am.ActivityManagerService.setLockScreenShown(ActivityManagerService.java:10780)
at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:668)
at com.android.server.am.ActivityManagerService.setLockScreenShown(<Xposed>)
at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:1336)
at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2521)
at com.android.server.am.ActivityManagerServiceEx.onTransact(ActivityManagerServiceEx.java:448)
at android.os.Binder.execTransact(Binder.java:446)
at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:668)
at android.os.Binder.execTransact(<Xposed>)

java.lang.NoSuchFieldException: mSleeping uid=1000
java.lang.NoSuchFieldException: mSleeping
at java.lang.Class.getDeclaredField(Class.java:890)
at biz.bokhorst.xprivacy.XActivityManagerService.b(SourceFile:192)
at biz.bokhorst.xprivacy.XPrivacy$XMethodHook.afterHookedMethod(SourceFile:660)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:682)
at com.android.server.am.ActivityManagerService.updateSleepIfNeededLocked(<Xposed>)
at com.android.server.am.ActivityManagerService.setLockScreenShown(ActivityManagerService.java:10780)
at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:668)
at com.android.server.am.ActivityManagerService.setLockScreenShown(<Xposed>)
at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:1336)
at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2521)
at com.android.server.am.ActivityManagerServiceEx.onTransact(ActivityManagerServiceEx.java:448)
at android.os.Binder.execTransact(Binder.java:446)
at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:668)
at android.os.Binder.execTransact(<Xposed>)

**Comment by mountbraindevnull** [comment]
+1

I'm not a coder. Don't know if it's helpful to know Xposed's log?
