### ISSUE TITLE
XPrivacy: internal check failed

### ISSUE THREAD

**Issue by Zenobiusz** [M66B/XPrivacy#2369]
What I did wrong? Too much apps frozen?

========

XPrivacy: 3.6.19 
Android: 6.0 (SDK 23) 
Huawei P8 lite (ALE-L21)

java.lang.NoSuchFieldException: No field mSleeping in class Lcom/android/server/am/HwActivityManagerService; (declaration of 'com.android.server.am.HwActivityManagerService' appears in /system/framework/hwServices.jar) uid=1000
java.lang.NoSuchFieldException: No field mSleeping in class Lcom/android/server/am/HwActivityManagerService; (declaration of 'com.android.server.am.HwActivityManagerService' appears in /system/framework/hwServices.jar)
at java.lang.Class.getDeclaredField(Native Method)
at biz.bokhorst.xprivacy.XActivityManagerService.b(SourceFile:192)
at biz.bokhorst.xprivacy.XPrivacy$XMethodHook.afterHookedMethod(SourceFile:660)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:769)
at com.android.server.am.ActivityManagerService.updateSleepIfNeededLocked(<Xposed>)
at com.android.server.am.ActivityManagerService.setLockScreenShown(ActivityManagerService.java:10991)
at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:755)
at com.android.server.am.ActivityManagerService.setLockScreenShown(<Xposed>)
at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:1361)
at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2646)
at com.android.server.am.HwActivityManagerService.onTransact(HwActivityManagerService.java:359)
at android.os.Binder.execTransact(Binder.java:453)
at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:755)
at android.os.Binder.execTransact(<Xposed>)

java.lang.NoSuchFieldException: No field mSleeping in class Lcom/android/server/am/HwActivityManagerService; (declaration of 'com.android.server.am.HwActivityManagerService' appears in /system/framework/hwServices.jar) uid=1000
java.lang.NoSuchFieldException: No field mSleeping in class Lcom/android/server/am/HwActivityManagerService; (declaration of 'com.android.server.am.HwActivityManagerService' appears in /system/framework/hwServices.jar)
at java.lang.Class.getDeclaredField(Native Method)
at biz.bokhorst.xprivacy.XActivityManagerService.b(SourceFile:192)
at biz.bokhorst.xprivacy.XPrivacy$XMethodHook.afterHookedMethod(SourceFile:660)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:769)
at com.android.server.am.ActivityManagerService.updateSleepIfNeededLocked(<Xposed>)
at com.android.server.am.ActivityManagerService.onWakefulnessChanged(ActivityManagerService.java:10814)
at com.android.server.am.ActivityManagerService$LocalService.onWakefulnessChanged(ActivityManagerService.java:21496)
at com.android.server.power.Notifier$1.run(Notifier.java:329)
at android.os.Handler.handleCallback(Handler.java:743)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:150)
at com.android.server.SystemServer.run(SystemServer.java:388)
at com.android.server.SystemServer.main(SystemServer.java:268)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:133)

java.lang.NoSuchFieldException: No field mSleeping in class Lcom/android/server/am/HwActivityManagerService; (declaration of 'com.android.server.am.HwActivityManagerService' appears in /system/framework/hwServices.jar) uid=1000
java.lang.NoSuchFieldException: No field mSleeping in class Lcom/android/server/am/HwActivityManagerService; (declaration of 'com.android.server.am.HwActivityManagerService' appears in /system/framework/hwServices.jar)
at java.lang.Class.getDeclaredField(Native Method)
at biz.bokhorst.xprivacy.XActivityManagerService.b(SourceFile:192)
at biz.bokhorst.xprivacy.XPrivacy$XMethodHook.afterHookedMethod(SourceFile:660)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:769)
at com.android.server.am.ActivityManagerService.updateSleepIfNeededLocked(<Xposed>)
at com.android.server.am.ActivityManagerService.onWakefulnessChanged(ActivityManagerService.java:10814)
at com.android.server.am.ActivityManagerService$LocalService.onWakefulnessChanged(ActivityManagerService.java:21496)
at com.android.server.power.Notifier$1.run(Notifier.java:329)
at android.os.Handler.handleCallback(Handler.java:743)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:150)
at com.android.server.SystemServer.run(SystemServer.java:388)
at com.android.server.SystemServer.main(SystemServer.java:268)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:133)

java.lang.NoSuchFieldException: No field mSleeping in class Lcom/android/server/am/HwActivityManagerService; (declaration of 'com.android.server.am.HwActivityManagerService' appears in /system/framework/hwServices.jar) uid=1000
java.lang.NoSuchFieldException: No field mSleeping in class Lcom/android/server/am/HwActivityManagerService; (declaration of 'com.android.server.am.HwActivityManagerService' appears in /system/framework/hwServices.jar)
at java.lang.Class.getDeclaredField(Native Method)
at biz.bokhorst.xprivacy.XActivityManagerService.b(SourceFile:192)
at biz.bokhorst.xprivacy.XPrivacy$XMethodHook.afterHookedMethod(SourceFile:660)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:769)
at com.android.server.am.ActivityManagerService.updateSleepIfNeededLocked(<Xposed>)
at com.android.server.am.ActivityManagerService$LocalService.acquireSleepToken(ActivityManagerService.java:21513)
at com.android.server.policy.PhoneWindowManager.updateScreenOffSleepToken(PhoneWindowManager.java:7032)
at com.android.server.policy.PhoneWindowManager.screenTurnedOff(PhoneWindowManager.java:6227)
at com.android.server.policy.HwPhoneWindowManager.screenTurnedOff(HwPhoneWindowManager.java:2664)
at com.android.server.display.DisplayPowerController.setScreenState(DisplayPowerController.java:1154)
at com.android.server.display.DisplayPowerController.animateScreenStateChange(DisplayPowerController.java:1308)
at com.android.server.display.DisplayPowerController.updatePowerState(DisplayPowerController.java:833)
at com.android.server.display.DisplayPowerController.access$2600(DisplayPowerController.java:94)
at com.android.server.display.DisplayPowerController$DisplayControllerHandler.handleMessage(DisplayPowerController.java:1758)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:150)
at android.os.HandlerThread.run(HandlerThread.java:61)
at com.android.server.ServiceThread.run(ServiceThread.java:46)

java.lang.NoSuchFieldException: No field mSleeping in class Lcom/android/server/am/HwActivityManagerService; (declaration of 'com.android.server.am.HwActivityManagerService' appears in /system/framework/hwServices.jar) uid=1000
java.lang.NoSuchFieldException: No field mSleeping in class Lcom/android/server/am/HwActivityManagerService; (declaration of 'com.android.server.am.HwActivityManagerService' appears in /system/framework/hwServices.jar)
at java.lang.Class.getDeclaredField(Native Method)
at biz.bokhorst.xprivacy.XActivityManagerService.b(SourceFile:192)
at biz.bokhorst.xprivacy.XPrivacy$XMethodHook.afterHookedMethod(SourceFile:660)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:769)
at com.android.server.am.ActivityManagerService.updateSleepIfNeededLocked(<Xposed>)
at com.android.server.am.ActivityManagerService.onWakefulnessChanged(ActivityManagerService.java:10814)
at com.android.server.am.ActivityManagerService$LocalService.onWakefulnessChanged(ActivityManagerService.java:21496)
at com.android.server.power.Notifier$1.run(Notifier.java:329)
at android.os.Handler.handleCallback(Handler.java:743)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:150)
at com.android.server.SystemServer.run(SystemServer.java:388)
at com.android.server.SystemServer.main(SystemServer.java:268)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:133)

**Comment by M66B** [comment]
There is a already an issue for this

**Comment by M66B** [comment]
Please read also this:
https://github.com/M66B/XPrivacy#support
