### ISSUE TITLE
Unable to get pro version

### ISSUE THREAD

**Issue by Genhis** [M66B/XPrivacy#2410]
Hello,

I'm unable to get pro version of XPrivacy.

The license file has its original name and content.

I tried several locations, including:

- SD card root directory
- internal storage root directory
- /storage/emulated/0 (which is listed in About section, I guess that's the internal storage) and /storage/emulated/0/Download
- /data/data/biz.bokhorst.xprivacy/

I also tried opening the file in XPrivacy, with no success.

Every time when XPrivacy starts, it gives an error (internal check failed). Might it be related?

```
XPrivacy: 3.6.19
Android: 6.0 (SDK 23)

Brand: Huawei
Manufacturer: HUAWEI
Model: ALE-L21
Product: ALE-L21
Device: hwALE-H
Host: localhost#1
Display: ALE-L21C432B594
Id: HuaweiALE-L21

java.lang.NoSuchFieldException: No field mSleeping in class Lcom/android/server/am/HwActivityManagerService; (declaration of 'com.android.server.am.HwActivityManagerService' appears in /system/framework/hwServices.jar) uid=1000
java.lang.NoSuchFieldException: No field mSleeping in class Lcom/android/server/am/HwActivityManagerService; (declaration of 'com.android.server.am.HwActivityManagerService' appears in /system/framework/hwServices.jar)
	at java.lang.Class.getDeclaredField(Native Method)
	at biz.bokhorst.xprivacy.XActivityManagerService.b(SourceFile:192)
	at biz.bokhorst.xprivacy.XPrivacy$XMethodHook.afterHookedMethod(SourceFile:660)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:769)
	at com.android.server.am.ActivityManagerService.updateSleepIfNeededLocked(<Xposed>)
	at com.android.server.am.ActivityManagerService.setLockScreenShown(ActivityManagerService.java:11217)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:755)
	at com.android.server.am.ActivityManagerService.setLockScreenShown(<Xposed>)
	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:1361)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2703)
	at com.android.server.am.HwActivityManagerService.onTransact(HwActivityManagerService.java:393)
	at android.os.Binder.execTransact(Binder.java:453)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:755)
	at android.os.Binder.execTransact(<Xposed>)
```

I'm using Xposed installer and framework from this thread: https://forum.xda-developers.com/p8lite/general/mega-thread-root-unbricking-updating-t3400994

Any ideas what else could I try?

Thank you in advance.

**Comment by M66B** [comment]
Please reply to the activation instructions for support.

**Comment by eltirol** [comment]
Grax
