### ISSUE TITLE
Internal Check Failed on app launch

### ISSUE THREAD

**Issue by mistikal** [M66B/XPrivacy#2422]
Many thanks for this excellent module,  have used it for a number of years on my old phone however I cannot seem to make it work on the new phone. 

Xposed has the module enabled, other modules appear to work fine, however it seems the Xprivacy module does not want to do anything. Also of note, only a small handful of apps show in the module, not most/all.

XPrivacy: 3.6.19
Android: 6.0.1 (SDK 23)

Brand: OPPO
Manufacturer: OPPO
Model: CPH1611
Product: CPH1611
Device: CPH1611
Host: WX-122-114
Display: CPH1611EX_11_A.04_170204
Id: MMB29M

java.lang.NoSuchFieldException: No field mSleeping in class Lcom/android/server/am/OppoActivityManagerService; (declaration of 'com.android.server.am.OppoActivityManagerService' appears in /system/framework/services.jar) uid=1000
java.lang.NoSuchFieldException: No field mSleeping in class Lcom/android/server/am/OppoActivityManagerService; (declaration of 'com.android.server.am.OppoActivityManagerService' appears in /system/framework/services.jar)
	at java.lang.Class.getDeclaredField(Native Method)
	at biz.bokhorst.xprivacy.XActivityManagerService.b(SourceFile:192)
	at biz.bokhorst.xprivacy.XPrivacy$XMethodHook.afterHookedMethod(SourceFile:660)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
	at com.android.server.am.ActivityManagerService.updateSleepIfNeededLocked(<Xposed>)
	at com.android.server.am.ActivityManagerService.setLockScreenShown(ActivityManagerService.java:11999)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
	at com.android.server.am.ActivityManagerService.setLockScreenShown(<Xposed>)
	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:1377)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2952)
	at com.android.server.am.OppoActivityManagerService.onTransact(OppoActivityManagerService.java:168)
	at android.os.Binder.execTransact(Binder.java:453)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
	at android.os.Binder.execTransact(<Xposed>)

java.lang.NoSuchFieldException: No field mSleeping in class Lcom/android/server/am/OppoActivityManagerService; (declaration of 'com.android.server.am.OppoActivityManagerService' appears in /system/framework/services.jar) uid=1000
java.lang.NoSuchFieldException: No field mSleeping in class Lcom/android/server/am/OppoActivityManagerService; (declaration of 'com.android.server.am.OppoActivityManagerService' appears in /system/framework/services.jar)
	at java.lang.Class.getDeclaredField(Native Method)
	at biz.bokhorst.xprivacy.XActivityManagerService.b(SourceFile:192)
	at biz.bokhorst.xprivacy.XPrivacy$XMethodHook.afterHookedMethod(SourceFile:660)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
	at com.android.server.am.ActivityManagerService.updateSleepIfNeededLocked(<Xposed>)
	at com.android.server.am.ActivityManagerService.setLockScreenShown(ActivityManagerService.java:11999)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
	at com.android.server.am.ActivityManagerService.setLockScreenShown(<Xposed>)

**Comment by M66B** [comment]
A similar issue already exists.
